import type { DeveloperDetail } from "@/features/developers/types";
import type { ProjectDetail, ProjectSummary } from "@/features/projects/types";

const image = (seed: string) =>
  `https://images.unsplash.com/${seed}?auto=format&fit=crop&w=1200&q=80`;

export const mockProjects: ProjectDetail[] = [
  {
    id: "project-aurora",
    developerProfileId: "dev-novastone",
    developerName: "Novastone Developments",
    developerSlug: "novastone-developments",
    title: "Aurora Residences",
    slug: "aurora-residences",
    description:
      "A waterfront residential project positioned for buyers seeking premium amenities, strong architecture, and an address-led lifestyle pitch.",
    location: "Dubai Marina, Dubai",
    city: "Dubai",
    country: "United Arab Emirates",
    minPrice: 420000,
    maxPrice: 1350000,
    currencyCode: "USD",
    status: "active",
    approvalStatus: "approved",
    projectType: "apartment",
    completionStage: "under_construction",
    isFeatured: true,
    latitude: 25.0804,
    longitude: 55.1403,
    heroMediaUrl: image("photo-1460317442991-0ec209397118"),
    media: [
      {
        id: "media-1",
        projectId: "project-aurora",
        mediaType: "image",
        fileUrl: image("photo-1460317442991-0ec209397118"),
        thumbnailUrl: image("photo-1460317442991-0ec209397118"),
        title: "Main exterior",
        sortOrder: 0,
      },
      {
        id: "media-2",
        projectId: "project-aurora",
        mediaType: "brochure",
        fileUrl: "https://example.com/brochures/aurora.pdf",
        thumbnailUrl: null,
        title: "Project brochure",
        sortOrder: 1,
      },
      {
        id: "media-3",
        projectId: "project-aurora",
        mediaType: "tour_3d",
        fileUrl: "https://matterport.com/discover/space/example-aurora",
        thumbnailUrl: null,
        title: "3D walkthrough",
        sortOrder: 2,
      },
    ],
  },
  {
    id: "project-canyon",
    developerProfileId: "dev-redcliff",
    developerName: "Redcliff Urban",
    developerSlug: "redcliff-urban",
    title: "Canyon Square",
    slug: "canyon-square",
    description:
      "A mixed-use development designed for investors and urban buyers, combining residential inventory, retail frontage, and a public plaza.",
    location: "Riyadh North, Riyadh",
    city: "Riyadh",
    country: "Saudi Arabia",
    minPrice: 310000,
    maxPrice: 2200000,
    currencyCode: "USD",
    status: "active",
    approvalStatus: "approved",
    projectType: "mixed_use",
    completionStage: "pre_launch",
    isFeatured: false,
    latitude: 24.822,
    longitude: 46.643,
    heroMediaUrl: image("photo-1511818966892-d7d671e672a2"),
    media: [
      {
        id: "media-4",
        projectId: "project-canyon",
        mediaType: "image",
        fileUrl: image("photo-1511818966892-d7d671e672a2"),
        thumbnailUrl: image("photo-1511818966892-d7d671e672a2"),
        title: "Masterplan view",
        sortOrder: 0,
      },
      {
        id: "media-5",
        projectId: "project-canyon",
        mediaType: "video",
        fileUrl: "https://example.com/videos/canyon-square.mp4",
        thumbnailUrl: null,
        title: "Launch film",
        sortOrder: 1,
      },
    ],
  },
  {
    id: "project-serene",
    developerProfileId: "dev-novastone",
    developerName: "Novastone Developments",
    developerSlug: "novastone-developments",
    title: "Serene Villas",
    slug: "serene-villas",
    description:
      "A gated villa community built around landscaped streets, private plots, and resort-style shared amenities.",
    location: "New Cairo, Cairo",
    city: "Cairo",
    country: "Egypt",
    minPrice: 580000,
    maxPrice: 990000,
    currencyCode: "USD",
    status: "active",
    approvalStatus: "approved",
    projectType: "villa",
    completionStage: "ready",
    isFeatured: true,
    latitude: 30.0156,
    longitude: 31.4913,
    heroMediaUrl: image("photo-1505693416388-ac5ce068fe85"),
    media: [
      {
        id: "media-6",
        projectId: "project-serene",
        mediaType: "image",
        fileUrl: image("photo-1505693416388-ac5ce068fe85"),
        thumbnailUrl: image("photo-1505693416388-ac5ce068fe85"),
        title: "Villa exterior",
        sortOrder: 0,
      },
    ],
  },
];

export const mockProjectSummaries: ProjectSummary[] = mockProjects.map(
  (project) => ({
    id: project.id,
    developerProfileId: project.developerProfileId,
    developerName: project.developerName,
    developerSlug: project.developerSlug,
    title: project.title,
    slug: project.slug,
    description: project.description,
    location: project.location,
    city: project.city,
    country: project.country,
    minPrice: project.minPrice,
    maxPrice: project.maxPrice,
    currencyCode: project.currencyCode,
    status: project.status,
    approvalStatus: project.approvalStatus,
    projectType: project.projectType,
    completionStage: project.completionStage,
    isFeatured: project.isFeatured,
    latitude: project.latitude,
    longitude: project.longitude,
    heroMediaUrl: project.heroMediaUrl,
  }),
);

export const mockDevelopers: DeveloperDetail[] = [
  {
    id: "dev-novastone",
    userId: "user-novastone",
    companyName: "Novastone Developments",
    slug: "novastone-developments",
    description:
      "A regional developer focused on premium residential communities and hospitality-led living concepts.",
    websiteUrl: "https://example.com/novastone",
    logoUrl: null,
    isVerified: true,
    projects: mockProjectSummaries.filter(
      (project) => project.developerProfileId === "dev-novastone",
    ),
  },
  {
    id: "dev-redcliff",
    userId: "user-redcliff",
    companyName: "Redcliff Urban",
    slug: "redcliff-urban",
    description:
      "A developer focused on mixed-use urban districts with high-visibility commercial frontage and residential inventory.",
    websiteUrl: "https://example.com/redcliff",
    logoUrl: null,
    isVerified: true,
    projects: mockProjectSummaries.filter(
      (project) => project.developerProfileId === "dev-redcliff",
    ),
  },
];
