import type { DeveloperDetail } from "@/features/developers/types";
import type { ProjectDetail, ProjectSummary } from "@/features/projects/types";

const image = (seed: string) =>
  `https://images.unsplash.com/${seed}?auto=format&fit=crop&w=1400&q=80`;

export const mockProjects: ProjectDetail[] = [
  {
    id: "project-aurora",
    developerProfileId: "dev-novastone",
    developerName: "Novastone Developments",
    developerSlug: "novastone-developments",
    title: "Aurora Residences",
    slug: "aurora-residences",
    description:
      "A waterfront residential address designed around panoramic marina views, a private wellness floor, and hotel-grade resident services.",
    location: "Dubai Marina, Dubai",
    city: "Dubai",
    country: "United Arab Emirates",
    minPrice: 420000,
    maxPrice: 1350000,
    currencyCode: "USD",
    status: "active",
    approvalStatus: "approved",
    offerType: "sale",
    category: "residential",
    projectType: "apartment",
    completionStage: "under_construction",
    isFeatured: true,
    latitude: 25.0804,
    longitude: 55.1403,
    heroMediaUrl: image("photo-1460317442991-0ec209397118"),
    media: [
      {
        id: "media-1",
        projectId: "project-aurora",
        mediaType: "image",
        fileUrl: image("photo-1460317442991-0ec209397118"),
        thumbnailUrl: image("photo-1460317442991-0ec209397118"),
        title: "Main exterior",
        sortOrder: 0,
      },
      {
        id: "media-2",
        projectId: "project-aurora",
        mediaType: "brochure",
        fileUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
        thumbnailUrl: null,
        title: "Project brochure",
        sortOrder: 1,
      },
      {
        id: "media-3",
        projectId: "project-aurora",
        mediaType: "tour_3d",
        fileUrl: "https://matterport.com/discover/space/x7dR5DjK7Lm",
        thumbnailUrl: null,
        title: "3D walkthrough",
        sortOrder: 2,
      },
    ],
    units: [],
  },
  {
    id: "project-canyon",
    developerProfileId: "dev-redcliff",
    developerName: "Redcliff Urban",
    developerSlug: "redcliff-urban",
    title: "Canyon Square",
    slug: "canyon-square",
    description:
      "A mixed-use district combining premium apartments, boutique retail frontage, and a public plaza built for high footfall urban living.",
    location: "Riyadh North, Riyadh",
    city: "Riyadh",
    country: "Saudi Arabia",
    minPrice: 310000,
    maxPrice: 2200000,
    currencyCode: "USD",
    status: "active",
    approvalStatus: "approved",
    offerType: "sale",
    category: "commercial",
    projectType: "mixed_use",
    completionStage: "pre_launch",
    isFeatured: true,
    latitude: 24.822,
    longitude: 46.643,
    heroMediaUrl: image("photo-1511818966892-d7d671e672a2"),
    media: [
      {
        id: "media-4",
        projectId: "project-canyon",
        mediaType: "image",
        fileUrl: image("photo-1511818966892-d7d671e672a2"),
        thumbnailUrl: image("photo-1511818966892-d7d671e672a2"),
        title: "Masterplan view",
        sortOrder: 0,
      },
      {
        id: "media-5",
        projectId: "project-canyon",
        mediaType: "video",
        fileUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
        thumbnailUrl: null,
        title: "Launch film",
        sortOrder: 1,
      },
    ],
    units: [],
  },
  {
    id: "project-serene",
    developerProfileId: "dev-novastone",
    developerName: "Novastone Developments",
    developerSlug: "novastone-developments",
    title: "Serene Villas",
    slug: "serene-villas",
    description:
      "A gated villa community built around landscaped boulevards, private plots, and a resort-style leisure program.",
    location: "New Cairo, Cairo",
    city: "Cairo",
    country: "Egypt",
    minPrice: 580000,
    maxPrice: 990000,
    currencyCode: "USD",
    status: "active",
    approvalStatus: "approved",
    offerType: "sale",
    category: "residential",
    projectType: "villa",
    completionStage: "ready",
    isFeatured: false,
    latitude: 30.0156,
    longitude: 31.4913,
    heroMediaUrl: image("photo-1505693416388-ac5ce068fe85"),
    media: [
      {
        id: "media-6",
        projectId: "project-serene",
        mediaType: "image",
        fileUrl: image("photo-1505693416388-ac5ce068fe85"),
        thumbnailUrl: image("photo-1505693416388-ac5ce068fe85"),
        title: "Villa exterior",
        sortOrder: 0,
      },
    ],
    units: [],
  },
  {
    id: "project-oceanic",
    developerProfileId: "dev-bluecrest",
    developerName: "Bluecrest Estates",
    developerSlug: "bluecrest-estates",
    title: "Oceanic Crest",
    slug: "oceanic-crest",
    description:
      "A branded coastal apartment tower with panoramic sea views, private lounges, and hospitality-led amenities for global buyers.",
    location: "Jumeirah Beach, Dubai",
    city: "Dubai",
    country: "United Arab Emirates",
    minPrice: 690000,
    maxPrice: 3100000,
    currencyCode: "USD",
    status: "active",
    approvalStatus: "approved",
    offerType: "sale",
    category: "residential",
    projectType: "apartment",
    completionStage: "pre_launch",
    isFeatured: true,
    latitude: 25.2033,
    longitude: 55.2692,
    heroMediaUrl: image("photo-1449844908441-8829872d2607"),
    media: [
      {
        id: "media-7",
        projectId: "project-oceanic",
        mediaType: "image",
        fileUrl: image("photo-1449844908441-8829872d2607"),
        thumbnailUrl: image("photo-1449844908441-8829872d2607"),
        title: "Sea-facing facade",
        sortOrder: 0,
      },
    ],
    units: [],
  },
  {
    id: "project-orchid",
    developerProfileId: "dev-verde",
    developerName: "Verde Habitat",
    developerSlug: "verde-habitat",
    title: "Orchid Park Residences",
    slug: "orchid-park-residences",
    description:
      "A green-led townhouse development focused on family living, walkable streets, and low-density planning with strong landscaping identity.",
    location: "Mohammed Bin Rashid City, Dubai",
    city: "Dubai",
    country: "United Arab Emirates",
    minPrice: 760000,
    maxPrice: 1490000,
    currencyCode: "USD",
    status: "active",
    approvalStatus: "approved",
    offerType: "sale",
    category: "residential",
    projectType: "townhouse",
    completionStage: "under_construction",
    isFeatured: false,
    latitude: 25.1251,
    longitude: 55.2462,
    heroMediaUrl: image("photo-1600585154340-be6161a56a0c"),
    media: [
      {
        id: "media-8",
        projectId: "project-orchid",
        mediaType: "image",
        fileUrl: image("photo-1600585154340-be6161a56a0c"),
        thumbnailUrl: image("photo-1600585154340-be6161a56a0c"),
        title: "Community street view",
        sortOrder: 0,
      },
    ],
    units: [],
  },
  {
    id: "project-harbor",
    developerProfileId: "dev-summit",
    developerName: "Summit Harbour Group",
    developerSlug: "summit-harbour-group",
    title: "Harbor Exchange",
    slug: "harbor-exchange",
    description:
      "A premium commercial and office destination positioned for institutional tenants, waterfront retail, and long-term visibility.",
    location: "Doha Waterfront, Doha",
    city: "Doha",
    country: "Qatar",
    minPrice: 980000,
    maxPrice: 5400000,
    currencyCode: "USD",
    status: "active",
    approvalStatus: "approved",
    offerType: "rent",
    category: "office",
    projectType: "commercial",
    completionStage: "under_construction",
    isFeatured: false,
    latitude: 25.2854,
    longitude: 51.531,
    heroMediaUrl: image("photo-1486406146926-c627a92ad1ab"),
    media: [
      {
        id: "media-9",
        projectId: "project-harbor",
        mediaType: "image",
        fileUrl: image("photo-1486406146926-c627a92ad1ab"),
        thumbnailUrl: image("photo-1486406146926-c627a92ad1ab"),
        title: "Commercial frontage",
        sortOrder: 0,
      },
    ],
    units: [],
  },
];

export const mockProjectSummaries: ProjectSummary[] = mockProjects.map(
  (project) => ({
    id: project.id,
    developerProfileId: project.developerProfileId,
    developerName: project.developerName,
    developerSlug: project.developerSlug,
    title: project.title,
    slug: project.slug,
    description: project.description,
    location: project.location,
    city: project.city,
    country: project.country,
    minPrice: project.minPrice,
    maxPrice: project.maxPrice,
    currencyCode: project.currencyCode,
    status: project.status,
    approvalStatus: project.approvalStatus,
    offerType: project.offerType,
    category: project.category,
    projectType: project.projectType,
    completionStage: project.completionStage,
    isFeatured: project.isFeatured,
    latitude: project.latitude,
    longitude: project.longitude,
    heroMediaUrl: project.heroMediaUrl,
  }),
);

export const mockDevelopers: DeveloperDetail[] = [
  {
    id: "dev-novastone",
    userId: "user-novastone",
    companyName: "Novastone Developments",
    slug: "novastone-developments",
    description:
      "A regional developer focused on premium residential communities and hospitality-led living concepts.",
    websiteUrl: "https://example.com/novastone",
    logoUrl: null,
    isVerified: true,
    projects: mockProjectSummaries.filter(
      (project) => project.developerProfileId === "dev-novastone",
    ),
  },
  {
    id: "dev-redcliff",
    userId: "user-redcliff",
    companyName: "Redcliff Urban",
    slug: "redcliff-urban",
    description:
      "A mixed-use developer focused on urban districts, commercial frontage, and public realm-led planning.",
    websiteUrl: "https://example.com/redcliff",
    logoUrl: null,
    isVerified: true,
    projects: mockProjectSummaries.filter(
      (project) => project.developerProfileId === "dev-redcliff",
    ),
  },
  {
    id: "dev-bluecrest",
    userId: "user-bluecrest",
    companyName: "Bluecrest Estates",
    slug: "bluecrest-estates",
    description:
      "A luxury coastal developer focused on branded residences and high-spec waterfront living.",
    websiteUrl: "https://example.com/bluecrest",
    logoUrl: null,
    isVerified: true,
    projects: mockProjectSummaries.filter(
      (project) => project.developerProfileId === "dev-bluecrest",
    ),
  },
  {
    id: "dev-verde",
    userId: "user-verde",
    companyName: "Verde Habitat",
    slug: "verde-habitat",
    description:
      "A sustainability-led developer building low-density communities with strong landscaping and family-oriented planning.",
    websiteUrl: "https://example.com/verde",
    logoUrl: null,
    isVerified: false,
    projects: mockProjectSummaries.filter(
      (project) => project.developerProfileId === "dev-verde",
    ),
  },
  {
    id: "dev-summit",
    userId: "user-summit",
    companyName: "Summit Harbour Group",
    slug: "summit-harbour-group",
    description:
      "A commercial-led development group specializing in premium office, waterfront retail, and landmark mixed-use projects.",
    websiteUrl: "https://example.com/summit",
    logoUrl: null,
    isVerified: true,
    projects: mockProjectSummaries.filter(
      (project) => project.developerProfileId === "dev-summit",
    ),
  },
];
